//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetallicBlueDev.Sample.Data
{
    public partial class SampleEntity1
    {
        public int Id { get; set; }
        public int Value { get; set; }
    }
}
